name: CI

permissions:
  contents: read

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [main]

jobs:
  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@0.0.15
    with:
      license_header_check_project_name: "async-swiftly"
      api_breakage_check_enabled: false

  macos_checks:
    name: macOS Checks
    runs-on: xcode-27
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Swift version
        run: xcrun swift --version

      - name: Build and test
        run: xcrun swift test --parallel --enable-code-coverage

      - name: Generate coverage report
        shell: bash
        run: |
          shopt -s failglob
          objects=()
          for binary in .build/debug/*.xctest/Contents/MacOS/*; do
            objects+=(-object "$binary")
          done

          xcrun llvm-cov export \
            -format=lcov \
            -instr-profile=.build/debug/codecov/default.profdata \
            "${objects[@]}" \
            > coverage.lcov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.lcov
          disable_search: true
          fail_ci_if_error: true

  linux_checks:
    name: Linux Checks
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@0.0.15
    with:
      enable_windows_checks: false
      linux_swift_versions: "[\"nightly-6.4.x\"]"

  windows_checks:
    name: Windows Checks
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@0.0.15
    with:
      enable_linux_checks: false
      windows_swift_versions: "[\"nightly-6.4.x\"]"
